import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  zh: {
    "app.title": "如果不入侵，而是封鎖？",
    "app.subtitle": "CSIS 2025 兵棋推演報告核心發現",
    "intro.p1": "2028年，習近平決定改變台海現狀。但他沒有選擇風險極高的兩棲登陸入侵（Invasion），而是選擇了<b>「封鎖」(Blockade)</b>。CSIS 透過 26 次兵棋推演，模擬了各種封鎖情境。從單純的海警登船檢查，到全面的美中戰爭。",
    "intro.quote": "「封鎖不是入侵的前奏。入侵需要全面投入，而封鎖則是一種強制性的對話，雙方都保留了未使用的武力。」",
    "intro.quoteAuthor": "— 報告引言",
    "intro.p2": "這份報告打破了許多迷思。例如，封鎖並非「低風險、低成本」的選項；相反地，任何有效的封鎖都很容易升級為全面戰爭。而對台灣而言，撐下去的關鍵不在於飛彈數量，而在於<b>能源庫存</b>與<b>維持社會運轉的韌性</b>。",
    "section.context": "背景與脈絡",
    "section.context.sub": "封鎖為何成為可能的選項？",
    "section.history": "歷史的鏡子",
    "section.history.sub": "從柏林空運到灰色地帶法律戰",
    "section.method": "兵推方法論",
    "section.method.sub": "如何量化一個國家的窒息過程？",
    "section.geo": "地理戰略：三個關鍵變數",
    "section.geo.sub": "這是一場關於距離、港口與運量的後勤戰爭",
    "geo.zone": "封鎖排他區",
    "geo.zone.desc": "中國劃設的禁航區 (Exclusion Zone)，範圍大致重疊台灣防空識別區 (ADIZ)。在此區域內，商船將面臨登檢、扣押甚至攻擊，切斷絕大部分的正常航運。",
    "geo.route": "與那國-花蓮 生命線",
    "geo.route.desc": "距離僅100公里的短程護航走廊。由於台灣海峽被封鎖，這是美日台聯軍唯一能嘗試突破的通道，也是雙方海空軍激烈交戰的「鐵籠格鬥」場。",
    "geo.hub": "日本轉運樞紐",
    "geo.hub.desc": "因戰爭風險極高，國際遠洋商船不敢直航台灣。所有物資需先在日本港口卸貨，再轉由武裝或受保護的「穿梭船隊」運入台灣。",
    "section.matrix": "互動兵推 1: 結構化情境",
    "section.matrix.sub": "調整雙方交戰規則 (ROE)，觀察模型計算結果",
    "section.freeplay": "互動兵推 2: 自由演練",
    "section.freeplay.sub": "當人類介入決策：誤判、升級與下台階",
    "section.cost": "代價：血與鐵",
    "section.cost.sub": "結構化情境下的人員傷亡與商船損失",
    "section.energy": "核心弱點：能源生命線",
    "energy.title": "零基線測試：如果完全斷供？",
    "energy.desc": "CSIS 設定了「零基線」(Zero Baseline) 情境：假設封鎖完全成功，沒有任何物資進入。在此極端壓力測試下，<b>液化天然氣 (LNG)</b> 是最致命的弱點。即便在平時，台灣的 LNG 庫存也僅有約 11-12 天。",
    "energy.week3": "<strong>第 3 週：</strong> 天然氣耗盡。電力生產降至 73%，全台進入強制節電。",
    "energy.week9": "<strong>第 9 週：</strong> 燃煤耗盡。電力生產降至 24%，工業生產幾乎全面停擺。",
    "energy.week21": "<strong>第 21 週：</strong> 石油耗盡。電力生產降至 17%，僅剩核能與再生能源維持基本維生系統。",
    "energy.alert": "<strong>警訊：</strong> 報告指出，若台灣依照計畫廢除核能並過度依賴天然氣，其戰時能源韌性將顯著下降（見激進綠能情境）。",
    "section.impact": "社會衝擊：當電力消失時",
    "section.impact.sub": "電力短缺對各產業的連鎖反應",
    "section.global": "全球經濟衝擊",
    "section.policy": "政策模擬：我們該怎麼做？",
    "section.policy.sub": "試著組合不同政策，看看能否提升台灣的生存機率",
    "footer.title": "結語：準備，是為了避免戰爭",
    "footer.desc": "封鎖對中國而言並非零風險選項。若封鎖失敗或曠日費時，可能導致中國自身的經濟動盪與外交孤立。<br/><br/>台灣與美國的目標不在於贏得封鎖戰，而在於透過展示<b>「我們能撐得比你想像更久」</b>的能力，提高北京的決策成本，從而達到嚇阻的效果。",
    "footer.link": "閱讀完整報告 (CSIS.org)",
    "footer.note1": "本網站為基於 CSIS 2025年7月報告《Lights Out?: Wargaming a Chinese Blockade of Taiwan》製作的互動式導讀。",
    "footer.note2": "內容僅供教育與研究用途。All data derived from CSIS open-source wargame report.",
    
    "hero.tag": "CSIS 2025 特別報告",
    "hero.title.main": "Lights Out?",
    "hero.title.sub": "台灣封鎖兵棋推演",
    "hero.desc": "2028年，若中國決定封鎖台灣而非直接入侵，將會發生什麼？<br/>這份報告透過26次兵棋推演，揭示了能源、經濟與地緣政治的脆弱平衡。",
    "hero.start": "開始探索",

    "matrix.title": "升級階梯模擬器 (Escalation Matrix)",
    "matrix.desc": "CSIS 將衝突分為4個層級。請點擊下方按鈕，觀察當「中國」與「聯軍」處於不同交戰規則(ROE)時，戰況的變化。<br/>(註：此為固定情境模擬，真實的人為決策變數請參考下方的「自由演練」章節)",
    "matrix.china": "中國行動層級 (China)",
    "matrix.coalition": "聯軍/台灣行動層級 (Coalition)",
    "matrix.scenario": "SCENARIO",
    "matrix.electricity": "電力供應 (最差週)",
    "matrix.imports": "進口量 (最差週)",
    "matrix.casualties": "聯軍/中國傷亡",
    "matrix.casualties.desc": "預估作戰人員死亡數",
    "matrix.ships": "商船損失",
    "matrix.ships.desc": "艘 (擊沉或全損)",
    "matrix.desc_title": "情境描述",
    "matrix.summary_title": "分析總結",
    "matrix.insight_title": "戰術觀察",

    "casualties.title": "代價：人員傷亡與商船損失 (Casualties & Losses)",
    "casualties.desc": "隨著衝突層級升高，人員傷亡(柱狀)急劇增加，但商船損失(折線)因護航而減少。<br/><span class=\"text-xs text-red-500\">* 4x4 情境下，聯軍傷亡包含美軍航母被擊沉的巨大損失。</span>",
    "casualties.y_left": "人員傷亡數",
    "casualties.y_right": "商船損失數",
    "casualties.legend_coalition": "聯軍傷亡 (人)",
    "casualties.legend_china": "共軍傷亡 (人)",
    "casualties.legend_merchants": "商船損失 (艘)",
    "casualties.label1": "無傷亡",
    "casualties.label2": "台灣重創",
    "casualties.label3": "血腥護航",
    "casualties.label4": "災難性",
    "casualties.x_1x1": "1x1 (海警)",
    "casualties.x_2x2": "2x2 (潛艇)",
    "casualties.x_3x3": "3x3 (護航)",
    "casualties.x_4x4": "4x4 (全面)",

    "impact.sector": "產業/部門",
    "impact.power80": "電力 80%",
    "impact.power60": "電力 60%",
    "impact.power40": "電力 40%",
    "impact.power20": "電力 20%",

    "global.title": "為什麼世界無法袖手旁觀？",
    "global.desc": "如果說烏克蘭戰爭對全球經濟造成了陣痛，那麼台海封鎖將是一場心臟病發作。這不僅是地緣政治問題，更是全球經濟結構的崩潰。",
    "global.loss": "全球 GDP 損失預估",
    "global.trillion": "兆美元 (Trillion)",
    "global.low": "低強度封鎖 (Rhodium預估)",
    "global.high": "全面制裁與戰爭 (Bloomberg預估)",
    "global.ukraine": "烏克蘭戰爭影響",
    "global.taiwan": "台海戰爭預估影響",
    "global.chart_title": "經濟規模對比 (GDP)",
    "global.chart_unit": "單位：兆美元 (Trillions USD)",
    "global.note": "注：中國經濟規模是俄羅斯的8倍以上，這意味著制裁中國將對全球造成毀滅性反噬。",

    "sim.question": "核心問題",
    "sim.method": "分析方法",
    "sim.finding": "關鍵發現",

    "timeline.title": "通往 2028：危機如何升級？",
    "timeline.desc": "報告設定的情境並非憑空發生。從法律戰準備到軍事演習，中國已逐步建立實施「聯合封鎖戰役」的能力與正當性論述。",
    "timeline.click": "點擊查看戰略洞察",
    "timeline.insight": "Insight:",

    "history.tab1": "歷史與替代方案",
    "history.tab2": "法律戰：封鎖 vs. 隔離",
    "history.lesson.title": "歷史教訓：時間是關鍵",
    "history.lesson.desc": "歷史上的封鎖（如二戰時期盟軍對德國、日本的封鎖）通常需要數年才能生效。然而，CSIS 報告指出，現代精準打擊與台灣對能源的高度依賴，壓縮了這條時間線。",
    "history.berlin.title": "為什麼「柏林空運」模式不可行？",
    "history.berlin.desc": "許多人寄望於空運來突破封鎖。但數據顯示，台灣的需求量遠超歷史上任何空運行動的極限。空運僅能運送糧食與藥品，無法運送維持經濟所需的煤炭與天然氣。",
    "history.chart.tons": "每日噸數",
    "history.chart.caption": "每日物資需求/運量對比 (Tons/Day)",
    "history.legal.title": "名詞定義的戰爭",
    "history.legal.desc": "中國極可能避免使用「封鎖」(Blockade) 一詞，因為這是國際法上的戰爭行為。相反，他們會使用「隔離」(Quarantine) 或「執法」來模糊焦點。",
    "history.china.title": "中國論述：隔離/執法",
    "history.china.tag": "灰色地帶",
    "history.china.p1": "依據國內法（如海警法、反分裂法）執行。",
    "history.china.p2": "聲稱台灣為「叛亂省份」，此為內政問題。",
    "history.china.p3": "目標是迫使國際商船因保險費高漲而自動停駛，而非擊沉它們。",
    "history.coalition.title": "實際效應：軍事封鎖",
    "history.coalition.tag": "戰爭行為",
    "history.coalition.p1": "限制所有國家的船隻進出，符合國際法對封鎖的定義。",
    "history.coalition.p2": "台灣海峽是國際水域，阻礙航行違反海洋法公約。",
    "history.coalition.p3": "若實施布雷或擊沉商船，將立即升級為國際武裝衝突。",
    "history.insight": "關鍵 Insight：報告指出，美國不應像應對「入侵」那樣應對「封鎖」。反制封鎖需要更多的外交與法律戰準備，而非僅僅是軍事對抗。",

    "zero.title": "零基線測試 (Zero Baseline)",
    "zero.desc": "如果完全沒有任何物資進入台灣，我們會撐多久？<br/>此圖比較了三種不同能源政策下的生存曲線。",
    "zero.week": "當前模擬週數",
    "zero.y_axis": "電力供應 %",
    "zero.x_axis": "週數",
    "zero.event.gas": "天然氣耗盡",
    "zero.event.coal": "燃煤耗盡",
    "zero.event.oil": "石油耗盡",
    "zero.base": "現狀 (Base)",
    "zero.prepared": "有準備 (Prepared)",
    "zero.green": "激進綠能 (Green)",
    "zero.base.status1": "使用庫存中",
    "zero.prepared.desc": "增加戰略儲備 + 強制節電。",
    "zero.prepared.better": "比現狀多支撐",
    "zero.green.desc": "廢核+依賴天然氣。第3週即跌至嚴重水準(18%)，第7週進入危機。",

    "freeplay.title": "自由兵推 (Free Play): 當人類介入",
    "freeplay.desc": "電腦模型是線性的，但人類決策是混亂的。CSIS 邀請專家進行了5場無腳本兵推，結果顯示「升級」幾乎無法避免。",
    "freeplay.result": "結果:",
    "freeplay.scenario": "情境敘述",
    "freeplay.coalition_cas": "聯軍傷亡 (人)",
    "freeplay.china_cas": "共軍傷亡 (人)",

    "policy.title": "政策模擬器：打造韌性之島",
    "policy.desc": "我們無法控制中國何時行動，但可以控制台灣多難被擊倒。選擇政策組合，觀察「國家耐力」的變化。",
    "policy.score": "國家耐力評估 (Resilience Score)",
    "policy.prediction": "預測結果：",
    "policy.status.low": "高風險：台灣將在 3-4 週內面臨能源崩潰，迫使在國際介入前投降。",
    "policy.status.med": "中等韌性：能撐過初期衝擊，但長期仍需依賴美軍打破封鎖。",
    "policy.status.high": "高韌性：能源與物資能維持數月，給予外交斡旋與軍事準備充足時間。",
    "policy.status.fortress": "堅不可摧：封鎖對中國將變成昂貴且無效的消耗戰，有效嚇阻戰爭。",

    "rec.1.title": "1. 準備商船隊",
    "rec.1.content": "徵用機制與 LNG 船隊擴建",
    "rec.2.title": "2. 強化能源韌性",
    "rec.2.content": "電網加固與增加戰略庫存",
    "rec.3.title": "3. 美國援助計畫",
    "rec.3.content": "重啟護航演習與盟友協調",
    "rec.4.title": "4. 反制與結束",
    "rec.4.content": "建立外交聯盟與下台階機制",

    "map.title": "台海封鎖戰略圖",
    "map.desc": "點擊地圖上的元素查看詳情。這是一場地理與後勤的戰爭。",
    "map.china": "中國大陸",
    "map.taiwan": "台灣",
    "map.yonaguni": "與那國島",
    "map.okinawa": "沖繩 (美軍基地)",
    "map.ez": "封鎖排他區"
  },
  en: {
    "app.title": "If Not Invasion, Then Blockade?",
    "app.subtitle": "Key Findings from the CSIS 2025 Wargame Report",
    "intro.p1": "In 2028, Xi Jinping decides to alter the status quo in the Taiwan Strait. Instead of a high-risk amphibious invasion, he chooses a <b>\"Blockade\"</b>. CSIS simulated various blockade scenarios through 26 wargames, ranging from simple coast guard inspections to a full-scale US-China war.",
    "intro.quote": "\"A blockade is not a prelude to invasion. Invasion requires total commitment, while a blockade is a coercive dialogue where both sides retain unused force.\"",
    "intro.quoteAuthor": "— Report Introduction",
    "intro.p2": "This report shatters many myths. For instance, a blockade is not a \"low-risk, low-cost\" option; on the contrary, any effective blockade can easily escalate into a total war. For Taiwan, the key to survival lies not in the number of missiles, but in <b>energy reserves</b> and the <b>resilience to keep society running</b>.",
    "section.context": "Context & Timeline",
    "section.context.sub": "Why has a blockade become a possible option?",
    "section.history": "Mirror of History",
    "section.history.sub": "From the Berlin Airlift to Gray Zone Lawfare",
    "section.method": "Wargame Methodology",
    "section.method.sub": "How to quantify the suffocation of a nation?",
    "section.geo": "Strategic Geography: Three Key Variables",
    "section.geo.sub": "A logistics war about distance, ports, and volume",
    "geo.zone": "Exclusion Zone",
    "geo.zone.desc": "The exclusion zone declared by China, roughly overlapping with Taiwan's ADIZ. Within this area, merchant ships face boarding, seizure, or even attack, cutting off most normal shipping.",
    "geo.route": "Yonaguni-Hualien Lifeline",
    "geo.route.desc": "A short convoy corridor of only 100 km. With the Taiwan Strait blocked, this is the only channel the US-Japan-Taiwan coalition can attempt to breach, and it is also the \"cage fight\" arena for fierce air and naval battles.",
    "geo.hub": "Japan Transshipment Hub",
    "geo.hub.desc": "Due to extreme war risks, international ocean-going vessels dare not sail directly to Taiwan. All supplies must be unloaded at Japanese ports and then transported to Taiwan by armed or protected \"shuttle fleets\".",
    "section.matrix": "Interactive Wargame 1: Structured Scenarios",
    "section.matrix.sub": "Adjust Rules of Engagement (ROE) and observe model results",
    "section.freeplay": "Interactive Wargame 2: Free Play",
    "section.freeplay.sub": "When humans intervene: Miscalculation, Escalation, and Off-Ramps",
    "section.cost": "The Cost: Blood and Iron",
    "section.cost.sub": "Casualties and merchant ship losses in structured scenarios",
    "section.energy": "Core Vulnerability: Energy Lifeline",
    "energy.title": "Zero Baseline Test: What if supply is completely cut?",
    "energy.desc": "CSIS set a \"Zero Baseline\" scenario: Assuming the blockade is completely successful and no supplies enter. Under this extreme stress test, <b>Liquefied Natural Gas (LNG)</b> is the most fatal weakness. Even in peacetime, Taiwan's LNG inventory is only about 11-12 days.",
    "energy.week3": "<strong>Week 3:</strong> Gas runs out. Power generation drops to 73%, island-wide rationing begins.",
    "energy.week9": "<strong>Week 9:</strong> Coal runs out. Power generation drops to 24%, industrial production almost completely halts.",
    "energy.week21": "<strong>Week 21:</strong> Oil runs out. Power generation drops to 17%, only nuclear and renewables remain to sustain basic life support systems.",
    "energy.alert": "<strong>Warning:</strong> The report notes that if Taiwan proceeds with plans to phase out nuclear power and over-relies on natural gas, its wartime energy resilience will drop significantly (see Aggressive Green Energy scenario).",
    "section.impact": "Social Impact: When the Lights Go Out",
    "section.impact.sub": "Chain reactions of power shortages across industries",
    "section.global": "Global Economic Impact",
    "section.policy": "Policy Simulation: What Should We Do?",
    "section.policy.sub": "Try combining different policies to see if Taiwan's survival probability improves",
    "footer.title": "Conclusion: Preparation is to Avoid War",
    "footer.desc": "For China, a blockade is not a zero-risk option. If the blockade fails or drags on, it could lead to economic turmoil and diplomatic isolation for China.<br/><br/>The goal for Taiwan and the US is not to win a blockade war, but to demonstrate the capability to <b>\"last longer than you imagine\"</b>, raising the cost of decision-making for Beijing and achieving deterrence.",
    "footer.link": "Read Full Report (CSIS.org)",
    "footer.note1": "This website is an interactive guide based on the July 2025 CSIS report \"Lights Out?: Wargaming a Chinese Blockade of Taiwan\".",
    "footer.note2": "Content is for educational and research purposes only. All data derived from CSIS open-source wargame report.",
    
    "hero.tag": "CSIS 2025 Special Report",
    "hero.title.main": "Lights Out?",
    "hero.title.sub": "Wargaming a Blockade",
    "hero.desc": "In 2028, what happens if China chooses a blockade over invasion?<br/>This report reveals the fragile balance of energy, economy, and geopolitics through 26 wargames.",
    "hero.start": "Start Exploring",

    "matrix.title": "Escalation Matrix Simulator",
    "matrix.desc": "CSIS categorizes conflict into 4 levels. Click buttons below to observe how the situation changes with different Rules of Engagement (ROE).<br/>(Note: This is a fixed scenario simulation; for human decision variables, see the \"Free Play\" section below)",
    "matrix.china": "China Action Level",
    "matrix.coalition": "Coalition Action Level",
    "matrix.scenario": "SCENARIO",
    "matrix.electricity": "Electricity (Worst Wk)",
    "matrix.imports": "Imports (Worst Wk)",
    "matrix.casualties": "Coalition/China Cas.",
    "matrix.casualties.desc": "Est. Combat Deaths",
    "matrix.ships": "Merchant Losses",
    "matrix.ships.desc": "Ships (Sunk/Total Loss)",
    "matrix.desc_title": "Description",
    "matrix.summary_title": "Summary",
    "matrix.insight_title": "Tactical Insight",

    "casualties.title": "Cost: Casualties & Losses",
    "casualties.desc": "As conflict escalates, casualties (bar) rise sharply, but merchant losses (line) decrease due to convoys.<br/><span class=\"text-xs text-red-500\">* In 4x4 scenario, coalition casualties include heavy losses from sinking of US carriers.</span>",
    "casualties.y_left": "Casualties (Count)",
    "casualties.y_right": "Merchant Losses (Ships)",
    "casualties.legend_coalition": "Coalition Cas.",
    "casualties.legend_china": "China Cas.",
    "casualties.legend_merchants": "Merchant Losses",
    "casualties.label1": "None",
    "casualties.label2": "TW Heavy Losses",
    "casualties.label3": "Bloody Convoy",
    "casualties.label4": "Catastrophic",
    "casualties.x_1x1": "1x1 (CG)",
    "casualties.x_2x2": "2x2 (Sub)",
    "casualties.x_3x3": "3x3 (Convoy)",
    "casualties.x_4x4": "4x4 (Total)",

    "impact.sector": "Sector",
    "impact.power80": "Power 80%",
    "impact.power60": "Power 60%",
    "impact.power40": "Power 40%",
    "impact.power20": "Power 20%",

    "global.title": "Why the World Cannot Stand By",
    "global.desc": "If the Ukraine war was a pain to the global economy, a Taiwan blockade would be a heart attack. This is not just geopolitics, but a collapse of the global economic structure.",
    "global.loss": "Est. Global GDP Loss",
    "global.trillion": "Trillion USD",
    "global.low": "Low Intensity (Rhodium)",
    "global.high": "Total Sanctions (Bloomberg)",
    "global.ukraine": "Ukraine War Impact",
    "global.taiwan": "Taiwan War Est.",
    "global.chart_title": "Economic Scale (GDP)",
    "global.chart_unit": "Unit: Trillions USD",
    "global.note": "Note: China's economy is 8x Russia's. Sanctioning China means devastating blowback for the world.",

    "sim.question": "Core Question",
    "sim.method": "Methodology",
    "sim.finding": "Key Finding",

    "timeline.title": "Road to 2028: How Crisis Escalates?",
    "timeline.desc": "The report's scenario is not ex nihilo. From legal warfare prep to military drills, China has gradually built the capability and justification for a \"Joint Blockade Campaign\".",
    "timeline.click": "Click to see strategic insight",
    "timeline.insight": "Insight:",

    "history.tab1": "History & Alternatives",
    "history.tab2": "Legal: Blockade vs Quarantine",
    "history.lesson.title": "Historical Lesson: Time is Key",
    "history.lesson.desc": "Historical blockades (e.g., WWII) took years to work. CSIS notes modern precision strikes and Taiwan's energy dependency compress this timeline.",
    "history.berlin.title": "Why \"Berlin Airlift\" won't work?",
    "history.berlin.desc": "Many hope for airlift. Data shows Taiwan's demand far exceeds any historical airlift limit. Airlift can bring food/meds, but not coal/gas for economy.",
    "history.chart.tons": "Tons/Day",
    "history.chart.caption": "Daily Demand vs Airlift Capacity (Tons/Day)",
    "history.legal.title": "War of Definitions",
    "history.legal.desc": "China will avoid \"Blockade\" (an act of war). Instead, they will use \"Quarantine\" or \"Law Enforcement\" to blur lines.",
    "history.china.title": "China's Narrative: Quarantine",
    "history.china.tag": "Gray Zone",
    "history.china.p1": "Based on domestic law (Coast Guard Law).",
    "history.china.p2": "Claims Taiwan is \"rebel province\", internal affair.",
    "history.china.p3": "Goal is to stop shipping via insurance rates, not sinking.",
    "history.coalition.title": "Actual Effect: Blockade",
    "history.coalition.tag": "Act of War",
    "history.coalition.p1": "Restricting all ships meets definition of blockade.",
    "history.coalition.p2": "Taiwan Strait is int'l waters; blocking violates UNCLOS.",
    "history.coalition.p3": "Mining or sinking ships escalates to conflict.",
    "history.insight": "Key Insight: The report notes US shouldn't treat \"Blockade\" like \"Invasion\". Countering blockade needs diplomatic/legal prep, not just military.",

    "zero.title": "Zero Baseline Test",
    "zero.desc": "If absolutely no supplies enter Taiwan, how long can we last?<br/>This chart compares survival curves under 3 energy policies.",
    "zero.week": "Current Week",
    "zero.y_axis": "Power Supply %",
    "zero.x_axis": "Weeks",
    "zero.event.gas": "Gas Out",
    "zero.event.coal": "Coal Out",
    "zero.event.oil": "Oil Out",
    "zero.base": "Base Case",
    "zero.prepared": "Prepared",
    "zero.green": "Aggressive Green",
    "zero.base.status1": "Using Inventory",
    "zero.prepared.desc": "Increased reserves + rationing.",
    "zero.prepared.better": "Lasts longer than base by",
    "zero.green.desc": "No Nuclear + Gas Reliance. Severe drop (18%) by Wk 3.",

    "freeplay.title": "Free Play: When Humans Intervene",
    "freeplay.desc": "Computer models are linear, but human decisions are chaotic. CSIS hosted 5 unscripted wargames, showing escalation is almost inevitable.",
    "freeplay.result": "Outcome:",
    "freeplay.scenario": "Scenario Description",
    "freeplay.coalition_cas": "Coalition Cas.",
    "freeplay.china_cas": "China Cas.",

    "policy.title": "Policy Simulator: Building a Resilient Island",
    "policy.desc": "We can't control when China moves, but we can control how hard Taiwan is to break. Choose policies to see \"Resilience Score\" change.",
    "policy.score": "Resilience Score",
    "policy.prediction": "Prediction:",
    "policy.status.low": "High Risk: Taiwan faces energy collapse in 3-4 weeks, forcing capitulation before int'l intervention.",
    "policy.status.med": "Medium: Survives initial shock, but long-term relies on US breaking blockade.",
    "policy.status.high": "High: Energy/supplies last months, giving ample time for diplomacy & military prep.",
    "policy.status.fortress": "Fortress: Blockade becomes expensive, ineffective war of attrition for China. Deterrence achieved.",

    "rec.1.title": "1. Merchant Prep",
    "rec.1.content": "Requisition & Expand LNG Fleet",
    "rec.2.title": "2. Energy Resilience",
    "rec.2.content": "Harden Grid & Increase Reserves",
    "rec.3.title": "3. US Support",
    "rec.3.content": "Convoy Drills & Ally Coordination",
    "rec.4.title": "4. End Game",
    "rec.4.content": "Diplomatic Coalition & Off-Ramps",

    "map.title": "Taiwan Blockade Strategic Map",
    "map.desc": "Click map elements for details. This is a war of geography and logistics.",
    "map.china": "Mainland China",
    "map.taiwan": "Taiwan",
    "map.yonaguni": "Yonaguni",
    "map.okinawa": "Okinawa (US Base)",
    "map.ez": "Exclusion Zone"
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
